AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'

Metrics/BlockLength:
    Exclude:
      - 'config/routes.rb'
      - 'Rakefile'
      - '**/*.rake'
      - 'spec/**/*.rb'
