require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'

RSpec/MultipleMemoizedHelpers:
  Enabled: false
    
Metrics/BlockLength:
    Exclude:
      - 'config/routes.rb'
      - 'config/environments/*'
      - 'Rakefile'
      - '**/*.rake'
      - 'spec/**/*.rb'

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
    - preview
