production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

staging:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/staging
    # read_timeout: 2
    # open_timeout: 0.5

frontend:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/frontend
    # read_timeout: 2
    # open_timeout: 0.5
    
preview:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/preview
    # read_timeout: 2
    # open_timeout: 0.5


    
development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/test
    
